import ProjectDescription

let workspace = Workspace(
    name: "Workspace",
    projects: ["Projects/**"],
    schemes: [
        .scheme(
            name: "development",
            shared: true,
            buildAction: .buildAction(targets: ["InOut"]),
            runAction: .runAction(executable: "InOut")
        ),
        .scheme(
            name: "production",
            shared: true,
            buildAction: .buildAction(targets: ["InOut"]),
            runAction: .runAction(executable: "InOut")
        )
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled
    )
)
